development:
  dialect: sqlite
  database: {{env "GOPATH" }}/src/github.com/bopbi/travel_server/db_development.sqlite

test:
  dialect: sqlite
  database: {{env "GOPATH" }}/src/github.com/bopbi/travel_server/db_test.sqlite

production:
  dialect: sqlite
  database: {{env "GOPATH" }}/src/github.com/bopbi/travel_server/db_production.sqlite
